In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("DABP_Raw_data.csv")

df = df.rename(columns={"eDispatch_01": "Disp_Complaint_Reported", "eDispatch_02": "EMD_Performed",
                        "eDisposition_12":"Patient_Disposition","eDisposition_19":"Final_Patient_Acuity",
                        "eDisposition_16":"Transport_Mode","eDisposition_21":"Destination",
                        "eDisposition_22":"Hospital_Inpatient_Destination",
                        "eOutcome_01":"Emergency_Department_Disposition","eOutcome_02":"Hospital_Disposition",
                       "ePatient_13":"Gender","ePatient_15":"Age","ePatient_16":"Age_Units",
                        "ePayment_50":"CMS_Service_Level","eResponse_05":"Response_Type_Service_Requested",
                       "eResponse_23":"Response_Mode_to_Scene","eScene_01":"First_EMS_Unit_Scene",
                        "eScene_06":"Number_of_Patients_Scene","eScene_07":"Mass_Casualty_Incident",
                       "eScene_08":"Triage_Classification_MCI","eScene_09":"Incident_Location_Type",
                       "eSituation_02":"Possible_Injury","'eSituation_07'":"Chief_Complaint_Anatomic_Location",
                       "'eSituation_08'":"Chief_Complaint_Organ_System","eSituation_13":"Initial_Patient_Acuity",
                       "'eSituation_01'":"Date/Time_of_Symptom_Onset","eTimes_01":"PSAP_Call_Date/Time",
                       "eTimes_03":"Unit_Notified_Dispatch_Date/Time","eTimes_05":"Unit_En_Route_Date/Time",
                       "eTimes_06":"Unit_Arrived on Scene Date/Time","eTimes_07":"Arrived_at_Patient_Date/Time",
                       "eTimes_09":"Unit_Left_Scene_Date/Time","eTimes_11":"Patient_Arrived_at_Destination_Date/Time",
                       "eTimes_12":"Destination_Patient_Transfer_of_Care_Date/Time",
                        "eTimes_13":"Unit Back in Service Date/Time","eDisposition_17":"Transport_Mode_from_Scene",
                       "CensusRegion":"Census_Region","CensusDivision":"Census_Division",
                       "'Urbanicity'":"Urbanicity","eHistory_17":"Alcohol/Drug_Use_Indicators","eInjury_01":"Cause_of_Injury",
                       "eDisposition_20":"Reason_for_Choosing_Destination","eDisposition_25":"Date/Time_of_Destination_Prearrival_Alert",
                       "eDisposition_24":"Destination_Team_Pre-Arrival_Alert","eResponse_08":"Type_of_Dispatch_Delay",
                       "eInjury_04":"Vehicular_Pedestrian_Injury_Risk_Factor","eSituation_09":"Primary_Symptom","eResponse_09":"Type_of_Response_Delay",
                       "eResponse_10":"Type_of_Scene_Delay","eResponse_11":"Type_of_Transport_Delay","eVitals_01":"Date/Time_Vital_Signs_Taken",
                       "eVitals_06":"Systolic_Blood_Pressure","eVitals_10":"Heart_Rate","eVitals_12":"Pulse_Oximetry","eVitals_14":"Respiratory_Rate",
                       "eVitals_16":"End_Tidal_Carbon_Dioxide","eVitals_18":"Blood_Glucose_Level","eVitals_27":"Pain_Scale_Score",
                       "eVitals_02":"Obtained_Prior_to_this_Unit_EMS_Care","eVitals_04":"ECG_Type","eVitals_08":"Method_of_Blood_Pressure_Measurement",
                       "eVitals_26":"Level_of_Responsiveness","eVitals_29":"Stroke_Scale_Score","eVitals_30":"Stroke_Scale_Type",
                        "eVitals_31":"Reperfusion_Checklist","eVitals_19":"Glasgow_Coma_Score_Eye","eVitals_20":"Glasgow_Coma_Score_Verbal",
                        "eVitals_21":"Glasgow_Coma_Score_Motor","ePatient_14":"Race","eHistory_01":"Barriers_to_Patient_Care",
                        "eMedications_03":"Date/Time_Medication_Administered","eMedications_05":"Medication_Dosage","eMedications_06":"Medication_Dosage_Units",
                        "eMedications_07":"Response_to_Medication","eMedications_10":"Role_of_Person_Administering_Medication",
                        "eMedications_02":"Medication_Administered_Prior_Unit_EMS_Care","eMedications_01":"Date/Time_Medication_Administered",
                        "eInjury_03":"Trauma_Center_Criteria"})

/var/folders/rl/dnlq62k50fd_dd8959xr62nh0000gn/T/ipykernel_19015/3629974227.py:1: DtypeWarning: Columns (77,82) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("DABP_Raw_data.csv")


In [3]:
df

PcrKey  Disp_Complaint_Reported  EMD_Performed  \
0        29723657                  2301021        2302007   
1        29723657                  2301021        2302007   
2        36585551                  2301059        7701003   
3        36585551                  2301059        7701003   
4        38930737                  2301071        7701001   
...           ...                      ...            ...   
1212637  80024875                  2301061        2302003   
1212638  80033457                  2301021        7701003   
1212639  80033457                  2301021        7701003   
1212640  80033457                  2301021        7701003   
1212641  80060190                  2301071        7701003   

         Patient_Disposition  Final_Patient_Acuity  Transport_Mode  \
0                    4212033               7701003         4216005   
1                    4212033               7701003         4216005   
2                    4212033               7701003         4216005   
3                    4212033               7701003         4216005   
4                    4212033               4219005         4216005   
...                      ...                   ...             ...   
1212637              4212033               4219005         4216005   
1212638              4212033               7701003         4216005   
1212639              4212033               7701003         4216005   
1212640              4212033               7701003         4216005   
1212641              4212033               4219005         4216005   

         Destination  Hospital_Inpatient_Destination  \
0            4221003                         7701003   
1            4221003                         7701003   
2            4221003                         7701003   
3            4221003                         7701003   
4            4221007                         7701001   
...              ...                             ...   
1212637      4221003                         7701001   
1212638      4221003                         7701001   
1212639      4221003                         7701001   
1212640      4221003                         7701001   
1212641      4221007                         7701001   

         Emergency_Department_Disposition  Hospital_Disposition  ...  \
0                                 7701003               7701003  ...   
1                                 7701003               7701003  ...   
2                                 7701003               7701003  ...   
3                                 7701003               7701003  ...   
4                                 7701003               7701003  ...   
...                                   ...                   ...  ...   
1212637                           7701003               7701003  ...   
1212638                           7701003               7701003  ...   
1212639                           7701003               7701003  ...   
1212640                           7701003               7701003  ...   
1212641                           7701003               7701003  ...   

         PcrMedicationKey  Date/Time_Medication_Administered  \
0               117368708                             317361   
1               117368708                             317361   
2               118882227                            7701003   
3               118882227                            7701003   
4               108893409                            7701001   
...                   ...                                ...   
1212637         125092049                                161   
1212638         125132750                               4917   
1212639         125132749                               4917   
1212640         125132750                               4917   
1212641         125178200                            7701003   

          eMedications_03Descr  Medication_Dosage  Medication_Dosage_Units  \
0        EPINEPHrine 0.1 MG/ML                1.0   

## Feature Selection
In this case, we are dealing with a lot of categorical variables with multiple interpretable meanings. Not much of the data can be interpreted numerically, and therefore we will have to either exclude it or develop our own numerical interpretation.

First is the outcome variable. We are trying to figure out what features are important for predicting patient death, therefore we can prioritize calls with those aspects when optimizing routing. We will use eoutcome 01 and eoutcome 02 for the outcome, which we will combine to form our y vector.

Keys with 20 indicates the patient has died either en route ot the hospital or while in the hospital's care, indicating it may be a situation where quicker response could have saved them. entries with 7701003 and 7701001 indicate that the column was not filed or not applicible, indicating no hospital transport. Therefore, these rows will be removed from our analysis.

In [4]:
ed_df = df.loc[(df['Emergency_Department_Disposition'] != 7701003) & (df['Emergency_Department_Disposition'] != 7701001)]

In [5]:
hosp_df = df.loc[(df['Hospital_Disposition'] != 7701003) & (df['Hospital_Disposition'] != 7701001)]

If a patient shows up in at least one of the two above dataframes, we know that they were transported to the hospial in the event

In [6]:
#Create index of all patients that were trainsported
transport_index = ed_df.index.union(hosp_df.index)

#
ML_df = df.iloc[transport_index]

In [7]:
ML_df = df.iloc[transport_index]

In [8]:
ML_df['patient_death'] = 0
ML_df.loc[(ML_df['Hospital_Disposition'] == 20) | (ML_df['Emergency_Department_Disposition'] == 20), 'patient_death'] = 1

/var/folders/rl/dnlq62k50fd_dd8959xr62nh0000gn/T/ipykernel_19015/4085509802.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ML_df['patient_death'] = 0


In [9]:
# 579 positive samples, the data is very unbalanced
ML_df.loc[ML_df['patient_death']==1]

PcrKey  Disp_Complaint_Reported  EMD_Performed  \
8348     74880607                  2301071        2302001   
8353     75042762                  2301071        2302001   
13501    64139813                  2301061        7701003   
19028    73122508                  2301013        2302007   
19472    62211091                  2301019        2302007   
...           ...                      ...            ...   
1189858  70230430                  2301077        7701003   
1190190  75531087                  2301041        2302001   
1203425  60495553                  2301073        2302003   
1205844  64919012                  2301019        2302007   
1210438  62936820                  2301033        2302007   

         Patient_Disposition  Final_Patient_Acuity  Transport_Mode  \
8348                 4212033               7701003         4216005   
8353                 4212033               4219005         4216005   
13501                4212033               7701003         4216005   
19028                4212033               4219003         4216005   
19472                4212033               4219001         4216005   
...                      ...                   ...             ...   
1189858              4212033               4219007         4216005   
1190190              4212033               4219001         4216005   
1203425              4212033               4219001         4216005   
1205844              4212033               4219001         4216005   
1210438              4212033               4219001         4216005   

         Destination  Hospital_Inpatient_Destination  \
8348         4221005                         4222035   
8353         4221005                         7701003   
13501        4221003                         7701001   
19028        4221003                         4222035   
19472        4221005                         4222035   
...              ...                             ...   
1189858      4221003                         7701003   
1190190      4221003                         7701003   
1203425      4221015                         7701003   
1205844      4221003                         7701003   
1210438      4221003                         7701003   

         Emergency_Department_Disposition  Hospital_Disposition  ...  \
8348                              7701003                    20  ...   
8353                                   20               7701003  ...   
13501                                   9                    20  ...   
19028                                   9                    20  ...   
19472                                  20                    20  ...   
...                                   ...                   ...  ...   
1189858                           7701003                    20  ...   
1190190                                 9                    20  ...   
1203425                                 9                    20  ...   
1205844                                20                    20  ...   
1210438                           7701003                    20  ...   

         Date/Time_Medication_Administered   eMedications_03Descr  \
8348                                  7806                 Oxygen   
8353                               7701003           Not Recorded   
13501                                  703             Amiodarone   
19028                                 7806                 Oxygen   
19472                                 7242               Naloxone   
...                                    ...                    ...   
1189858                             328316    Epinephrine 1 MG/ML   
1190190                             317361  EPINEPHrine 0.1 MG/ML   
1203425                               7806                 Oxygen   
1205844                             317361  EPINEPHrine 0.1 MG/ML   
1210438                             317361  EPINEPHrine 0.1 MG/ML   

         Medication_Dosage  Medication_Dosage_Units  Response_to_Medic

In [10]:
ML_df['Date/Time_Medication_Administered']

Date/Time_Medication_Administered Date/Time_Medication_Administered
81                                7701003                      Not Recorded
283                                  7806               2019-11-28 19:46:41
338                               7701003                      Not Recorded
339                               7701003                      Not Recorded
390                               7701003                      Not Recorded
...                                   ...                               ...
1212234                           7701003                      Not Recorded
1212288                           7701003                      Not Recorded
1212335                           7701001                    Not Applicable
1212380                           7701003                      Not Recorded
1212505                            237648               2019-04-23 18:50:00

[18928 rows x 2 columns]

In [11]:
def process_column(df:pd.DataFrame, colname:str, categorical:bool, func=None, convert_NA:bool=False):

    null_like = [7701003, 7701001, ]
    
    #Assumes that columns are singular, if not, drop all but the first
    if len(df[colname].columns > 1):
        extra_cols = df.colname.columns[1:]
        df.drop(columns=extra_cols, inplace=True)

    if convert_NA:
        df[colname].replace(to_replace=null_like, value=pd.NA, inplace=True)

    if categorical:
        pd.get_dummies(df, columns=colname, )

    if func is not None:
        df[colname] = df[colname].apply(func, convertDType=True)

    return None

    
    

In [12]:
selected_cols = [
    'Alcohol/Drug_Use_Indicators', #Convert to binary drug invovlement score
    'Barriers_to_Patient_Care', #Raw categorical
    'Cause_of_Injury', #Raw categorical
    'Reason_for_Choosing_Destination', #Raw categorical
    # 'Date/Time_Medication_Administered', 
    'Primary_Symptom', #Raw categorical
    'Gender', #Raw categorical
    'Age', #Numerical, convert NA
    'Heart_Rate', #Numerical, convert NA
    'Pulse_Oximetry', #Numerical, convert NA
    'Stroke_Scale_Score',#Numerical, convert NA
    'Glasgow_Coma_Score_Eye', #Numerical, convert NA
    'Blood_Glucose_Level', #Numerical, convert NA
    'Type_of_Dispatch_Delay', #Convert to binary if delayed or not
    'Type_of_Response_Delay', #ditto
    'Type_of_Scene_Delay', #ditto
    'Type_of_Transport_Delay', #ditto
    # Combine the above to determine if delayed or not (add cutoff parameter?)
        # Will not be part of the function, break out that segment

]

In [13]:
ML_df = ML_df[selected_cols]

In [14]:
ML_df

Alcohol/Drug_Use_Indicators  Barriers_to_Patient_Care  \
81                           8801015                   3101027   
283                          7701003                   3101009   
338                          7701003                   7701003   
339                          7701003                   7701003   
390                          8801015                   3101009   
...                              ...                       ...   
1212234                      8801015                   3101009   
1212288                      7701003                   3101009   
1212335                      7701001                   3101027   
1212380                      8801015                   3101009   
1212505                      8801015                   3101003   

        Cause_of_Injury  Reason_for_Choosing_Destination Primary_Symptom  \
81              7701001                          4220017          F03.91   
283             7701001                          4220001          R06.02   
338             7701003                          4220001          R41.82   
339             7701003                          4220001          R41.82   
390             7701003                          4220015          R41.82   
...                 ...                              ...             ...   
1212234           V49.9                          4220001           M54.9   
1212288           V03.1                          4220021          R07.89   
1212335         7701001                          4220021          R06.02   
1212380         7701003                          4220021           R46.3   
1212505         7701003                          4220021             R06   

          Gender      Age  Heart_Rate  Pulse_Oximetry  Stroke_Scale_Score  \
81       9906003       75          53              94             7701003   
283      9906001       75          90              97             3329001   
338      9906001       85     7701003         7701003             3329001   
339      9906001       85     7701003         7701003             7701003   
390      9906001       59          90              99             3329001   
...          ...      ...         ...             ...                 ...   
1212234  9906001       26     7701003         7701003             7701003   
1212288  9906003        7         106              99             7701001   
1212335  9906003       67         125              98             7701001   
1212380  9906003       29          76              96             7701003   
1212505  9906001  7701003         133              98             7701003   

         Glasgow_Coma_Score_Eye  Blood_Glucose_Level  Type_of_Dispatch_Delay  \
81                            4              7701003                 2208013   
283                           4              7701003                 2208013   
338                     7701003              7701003                 7701003   
339                           4              7701003                 7701003   
390                           4                  215                 2208013   
...                         ...                  ...                     ...   
1212234                 7701003              7701003                 7701003   
1212288                       4              7701003                 2208013   
1212335                       1              7701001                 7701003   
1212380                       4              7701003                 2208013   
1212505                       4                   91                 2208013   

         Type_of_Response_Delay  Type_of_Scene_Delay  Type_of_Transport_Delay  
81                      2209011              7701003                  7701003  
283                     2209011              2210017                  2211011  
338                     2209011              2210017                  2211011  
339                     2209011              2210017                  2211011  
390              

In [15]:
categoricals = [
    'Barriers_to_Patient_Care', #Raw categorical
    'Cause_of_Injury', #Raw categorical
    'Reason_for_Choosing_Destination', #Raw categorical
    'Primary_Symptom', #Raw categorical
    'Gender', #Raw categorical
]

numericals = [
    'Age', #Numerical, convert NA
    'Heart_Rate', #Numerical, convert NA
    'Pulse_Oximetry', #Numerical, convert NA
    'Stroke_Scale_Score',#Numerical, convert NA
    'Glasgow_Coma_Score_Eye', #Numerical, convert NA
    'Blood_Glucose_Level', #Numerical, convert NA 
]

modified = [
    'Alcohol/Drug_Use_Indicators', #Convert to binary drug invovlement score
    'Type_of_Dispatch_Delay', #Convert to binary if delayed or not
    'Type_of_Response_Delay', #ditto
    'Type_of_Scene_Delay', #ditto
    'Type_of_Transport_Delay', #ditto
]

In [16]:
#Convert categoricals

def convert_cats(df_in:pd.DataFrame, catlist:list):

    df = df_in.copy()

    #Ensure the column only shows up once, take the first one otherwize
    for colname in catlist:
        if type(df[colname]) != pd.Series:
            if len(df[colname].columns > 1):
                extra_cols = df.colname.columns[1:]
                df.drop(columns=extra_cols, inplace=True)

    cats_unrolled = pd.get_dummies(df, columns=categoricals)
    df = df.drop(columns=categoricals)

    return pd.concat([df, cats_unrolled], axis=1)


ML_df = convert_cats(ML_df, categoricals)

In [19]:
null_like = [7701003, 7701001, ]


def convert_numerical(df_in:pd.DataFrame, collist:list, null_like:list):

    df = df_in.copy()

    for colname in collist:
        #Remove extra columns
        if type(df[colname]) != pd.Series:
            if len(df[colname].columns) > 1:
                extra_cols = df[colname].columns[1:]
                df.drop(columns=extra_cols, inplace=True)

        
        col = df[colname].replace(to_replace=null_like, value=pd.NA, inplace=True)
        col = pd.to_numeric(col, errors='coerce')

        df[colname] = col

    return df


ML_df = convert_numerical(ML_df, numericals, null_like=null_like)

KeyError: 'Age'